Задания первых трёх разделов.
htmlacademy-php/1033347-doingsdone-12 pull request #1
Opened 2021-10-14 20:39 UTC by kondzerau-ivan

![2021-10-14_23-38](https://user-images.githubusercontent.com/24848155/137391964-d72a4e85-3f24-4e68-a3e0-108ac4ca381d.png)

2021-10-15 08:59 UTC, zenoleg requested changes
Основная логика в порядке!
Давай лишь причешем для будущего удобства

2021-10-15 08:59 UTC, zenoleg commented on app/config/config.php
> +$projects = ["Входящие", "Учеба", "Работа", "Домашние дела", "Авто"];
Правильно сделал, что вынес в отдельный файл.
Можно еще улучшить данный код, смотри.

Сейчас у нас в index.php IDE не понимает, откуда взялись переменные `$projects и $tasks`. 
![image](https://user-images.githubusercontent.com/38284534/137458607-1fd71f74-bcfd-4522-a7aa-7972f0bc3fa9.png)

И как ты понимаешь, в дальнейшем эти данные будут не захардкожены, а браться из БД.

Так вот, я предлагаю получение проектов и тасков сделать через функции. На текущем моменте функции будут возвращать захардкоженные массивы, а в дальнейшем просто перепишем логику функций на фетч данных из БД, и ничего не придется дальше переписывать.

**Жду функции:**
`function fetchTasks()
``function fetchProjects()`

2021-10-15 08:59 UTC, zenoleg commented on app/config/config.php
> +$projects = ["Входящие", "Учеба", "Работа", "Домашние дела", "Авто"];
Чем меньше магии в коде -- тем лучше. В идеале делать все явно

2021-10-15 08:59 UTC, zenoleg commented on app/config/config.php
> +$tasks = [
Еще советую сразу поставить плагин для PHPStorm: https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-

Так же посмотри отличие строк с двойными кавычками, и одинарными (https://profiphp.ru/useful/single_double_quotes.html)

В рантайме, для двойных кавычек, дергаются лишние проверки на вхождение переменных / спецсимволов. Экономия на копейках, но это стандарт)

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +                   <?php if ($show_complete_tasks === 1): ?>checked<?php endif; ?>
Можно проще, смотри:
```suggestion
                   <?= $show_complete_tasks === 1 ? 'checked' : '' ?>
```

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +                   <?php if ($show_complete_tasks === 1): ?>checked<?php endif; ?>
`<?=` короткий echo
ну а тернарный оператор должен быть тебе знаком

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +            <?php if($task["status"] === true && $show_complete_tasks === 0){ continue; } ?>
Молодец, что делаешь явное сравнение с true, респект!

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +            <tr class="tasks__item task <?php if ($task["status"] === true): ?>task--completed"<?php endif; ?> <?php if (isHotTask($task["date"])): ?>task--important<?php endif; ?>">
Тут стоит переделать условия на тернарный оператор, чтобы лучше читалось

2021-10-15 08:59 UTC, zenoleg commented on app/functions/functions.php
> +function tasksСounter($project_tasks, $project_title)
![image](https://user-images.githubusercontent.com/38284534/137459988-68fe6084-f0a9-42f0-81b0-a78dbb27fe3b.png)
Есть кирилица в названии

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +<section class="content__side">
![image](https://user-images.githubusercontent.com/38284534/137460333-0897e8cc-ef58-4107-8041-152fcd3d31d0.png)
Чтобы IDE от жизни не офигевала, стоит написать сверху PHPDOC.

```
<?php
/**
 * @var array $projects
 * @var array $tasks
 */
?>

<section class="content__side">
```

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +                    <a class="main-navigation__list-item-link" href="#"><?= htmlspecialchars($project); ?></a>
; в конце необязательны в данном случае, лучше убрать для красоты)
```suggestion
                    <a class="main-navigation__list-item-link" href="#"><?= htmlspecialchars($project) ?></a>
```

2021-10-15 08:59 UTC, zenoleg commented on app/templates/main.php
> +                    <span class="main-navigation__list-item-count"><?= tasksСounter($tasks, $project); ?></span>
Вызов какой-либо логики в шаблонах -- не самая хорошая практика.
Это можно посчитать до передачи в шаблон более эффективно, за один проход

2021-10-15 08:59 UTC, zenoleg commented on app/functions/functions.php
> +    if (!is_null($task_date)) {
Смотри, здесь получилась вложенность, из-за которой функция кажется нелинейной.
Можно сделать наоборот, сначала проверку на null, потом основная логика:

```
if ($taskDate === null) {
    return false;
}

// Остальная логика
```

2021-10-15 08:59 UTC, zenoleg commented on app/functions/functions.php
> +        if ($interval <= $period) {
Можно упростить:
Просто сделать

`return $interval <= $period;`

2021-10-15 09:30 UTC, kondzerau-ivan commented on app/templates/main.php
> +                   <?php if ($show_complete_tasks === 1): ?>checked<?php endif; ?>
Ну да, так читаемость повышается, меня что-то перемкнуло, что тернарнике, кода мы для false передаём пустую строку - это не очень красиво. Спасибо.

2021-10-15 09:32 UTC, kondzerau-ivan commented on app/templates/main.php
> +<section class="content__side">
Да я сам больше офигаваю, чем IDE, от того что не понимаю, чего оно подчёркивает и подсвечивает, что значение не определено, если всё по итогу определено и подходит. Вот выше ты написал про config.php и переделать передачу данных на функции - не знал, что так будет для IDE лучше. И про PHPDOC я первый раз вижу - почитаю. Спасибо!

2021-10-15 09:33 UTC, kondzerau-ivan commented on app/templates/main.php
> +                    <a class="main-navigation__list-item-link" href="#"><?= htmlspecialchars($project); ?></a>
Для красоты расставлял :) Ок, уберу.

2021-10-15 09:36 UTC, kondzerau-ivan commented on app/templates/main.php
> +                    <span class="main-navigation__list-item-count"><?= tasksСounter($tasks, $project); ?></span>
Так, вот тут не очень понимаю, как исправить. Ты не хочешь, чтобы я сюда функцию писал, тогда что здесь должно быть? И что должна в таком случае возвращать функция?

2021-10-16 08:40 UTC, kondzerau-ivan commented on app/functions/functions.php
> +    if (!is_null($task_date)) {
Здесь, кажется, лучше не возвращать false, а просто сделать выход из функции:
`if () { return; }`

2021-10-16 12:31 UTC, zenoleg commented on app/templates/main.php
> +<section class="content__side">
Если в файле не определена переменная -- она и будет подчеркнута как неизвестная.
Это лишь рекомендация

2021-10-18 18:27 UTC, zenoleg requested changes

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Поля с датой принято именовать аля `created_at`
Здесь `registered_at`

Так же давай использовать DATETIME, TIMESTAMP зависит от таймзоны БД, это слишком много логики на стороне базы. Все должно решать наше приложение на PHP.

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  email             VARCHAR(128) UNIQUE NOT NULL,
Дискриминация юзеров с мылом >128 символов. ~~Осуждаю!~~
[Линк на ознакомление со стандартом](https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address#:~:text=%22There%20is%20a%20length%20limit,total%20length%20of%20320%20characters.)

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  user_login        VARCHAR(128) UNIQUE NOT NULL,
Давай уберем префикс user, мы и так находимся в контексте таблицы `users`

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  project_title VARCHAR(128) UNIQUE NOT NULL,
Давай уберем префикс `project_`, так проще читать

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`created_at` лучше + давай на DATETIME перейдем

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  task_title    VARCHAR(128) NOT NULL,
Префикс `task_` давай уберем)

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  dead_line     TIMESTAMP DEFAULT 0,
`deadline` вполне себе существующее слово без пробелов)

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  dead_line     TIMESTAMP DEFAULT 0,
и дефолт нужен NULL, ибо по ТЗ дедлайн необязателен. 
А так у тебя всегда будет дедлайн просрочен, ибо timestamp 0 = 1970 год

2021-10-18 18:27 UTC, zenoleg commented on app/schema.sql
> +  dead_line     TIMESTAMP DEFAULT 0,
![image](https://user-images.githubusercontent.com/38284534/137786373-13c91ce0-1fdf-4146-a3f6-f00327126cf5.png)

2021-10-18 18:31 UTC, zenoleg requested changes

2021-10-18 18:31 UTC, zenoleg commented on app/queries.sql
> +       ('fedor@dostoevsky.com', 'Dostoevsky', 'zero123');
пароли хешируем. Можно встроенную функцию в мускуле MD5 использовать. 
Пример MD5('good_password')

2021-10-18 18:31 UTC, zenoleg commented on app/queries.sql
> +USE doingsdone;
Переделать после правок схемы

2021-10-18 18:31 UTC, zenoleg commented on app/queries.sql
> +VALUES ('Обновить програмное обеспечение',
Блин, давай каждое значение в одну строку, а то вообще не читается

2021-10-18 18:31 UTC, zenoleg commented on app/queries.sql
> +SELECT p.*, u.id
Звездочка это прикольно, но если схема БД в будущем изменится, то запрос будет получать лишние данные.

Давай явно напишем, какие поля получаем. Так и читать проще без оглядки на схему, и в будущем не будет проблем. Вдруг там одно поле удалится просто, а этот запрос с ошибкой не упадет -- не заметим баг

2021-10-18 18:33 UTC, kondzerau-ivan commented on app/queries.sql
> +       ('fedor@dostoevsky.com', 'Dostoevsky', 'zero123');
Типо, чтобы в базу уже захешированный прилетал?

2021-10-18 18:34 UTC, kondzerau-ivan commented on app/queries.sql
> +USE doingsdone;
А здесь что имеется ввиду "переделать"?

2021-10-18 18:37 UTC, kondzerau-ivan commented on app/queries.sql
> +SELECT p.*, u.id
Везде или конкретно в этом запросе?

2021-10-18 18:40 UTC, zenoleg commented on app/queries.sql
> +SELECT p.*, u.id
Звездочку везде убираем.

2021-10-18 18:41 UTC, zenoleg commented on app/queries.sql
> +USE doingsdone;
Как исправишь общую схему БД, запросы тоже надо будет переделать

2021-10-18 18:41 UTC, zenoleg commented on app/queries.sql
> +       ('fedor@dostoevsky.com', 'Dostoevsky', 'zero123');
угу

2021-10-19 10:26 UTC, merged